#!/bin/bash

# Define the output file
AUTHORS_FILE="AUTHORS.md"

# Create or overwrite AUTHORS.md
cat > "$AUTHORS_FILE" <<- EOF
# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

$(git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf | awk -F" " '{print $0}')
EOF

echo "AUTHORS.md file generated successfully."

